
title = "EventRelay"  # From Git
gitRepoUrl = "https://github.com/zebraKat/EventRelay" # From Git
gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "logo.svg"

# From git:
organizationName = "zebraKat"
projectName = "EventRelay"
url = "https://zebraKat.github.io"
baseUrl = "/EventRelay"
tagline = "Don't forget to listen!"
[navbar]

[footer]
style = "dark"
copyright = "Copyright © 2024 ZebraKat. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "Roblox"
href = "https://www.roblox.com/users/192119733/profile"

[API]

classOrder = [
    "EventRelay"
]

[home]
enabled = true
includeReadme = true # Optional

